### ISSUE TITLE
Add Laravel 5.4 compatibility

### ISSUE THREAD

**Issue by tpetry** [frenzyapp/turbolinks#14]
Laravel 5.4 support has been introduced with the stable laravel-stack-middleware 1.0 release.

**Comment by tortuetorche** [comment]
Hi Tobias,

FYI, I working on this (https://github.com/efficiently/turbolinks/tree/dev).
But `laravel-stack-middleware` 1.0 isn't compatible with Laravel 5.4 (https://github.com/barryvdh/laravel-stack-middleware/pull/10) yet.

Cheers,
Tortue Torche

**Comment by tpetry** [comment]
Oh, i assumed laravel 5.4 support is finished because the laravel-stack-middleware release 1.0.1 is described with laravel 5.4 support - didn't see you PR.

**Comment by tortuetorche** [comment]
Hi @tpetry,

It's done!
You should update your packages with the `frenzy/turbolinks` [3.1.0](https://github.com/frenzyapp/turbolinks/releases/tag/3.1.0) release:
`composer update`

Feel free to reopen this issue if you have any problems.

Have a good day,
Tortue Torche
