### ISSUE TITLE
JS not loaded perfectly

### ISSUE THREAD

**Issue by icangku** [frenzyapp/turbolinks#16]
I'm using Laravel 5.4, and almost every time i request page, its not loaded the javascripts files. How do i solve this?

**Comment by sasa-b** [comment]
Read the official [Turbolinks docs](https://github.com/turbolinks/turbolinks)

You should put  you `<script>` tags in the `<head>` of your document, and put the `defer` attribute on them (for performance, not to block the page execution), and you should add `data-turbolinks-track` attribute as well. Something like this:

```html
    <head>
          <script src="/turbolinks.js"></script>

          <script src="/your_app.js" defer data-turbolinks-track="reload"></script>

          <link href="/you_app.css" rel="stylesheets" type="text/css" data-turbolinks-track="reload">
```
