### ISSUE TITLE
Problem about facebook, backbone

### ISSUE THREAD

**Issue by mrminh231189** [frenzyapp/turbolinks#4]
I'm building website by laravel use backbone, api of facebook. When i use tuborlinks backbone and facebook don't run. Do you help me?
PS: Sorry because i speak english very bad ^^

**Comment by tortuetorche** [comment]
Hi @mrminh231189,

You should read this [article](http://reed.github.io/turbolinks-compatibility/facebook.html).

Cheers,
Tortue Torche
