### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by tortuetorche** [frenzyapp/turbolinks#6]
Hi @MathieuDoyon,

Few months ago, I forked your repository to integrate it with my [Larasset](https://github.com/efficiently/larasset/tree/1.0) package, which is an assets manager.
And now I've updated my [turbolinks fork](https://github.com/efficiently/turbolinks/tree/1.0) to support Laravel 5.

Here an [online demo](http://larasset.herokuapp.com) to see it in action with Laravel 5 and Larasset.

Maybe we can merge our repository? Because my fork has just a different installation instructions in the README.md and a line in the [ServiceProvider](https://github.com/efficiently/turbolinks/blob/1.0/src/Efficiently/Turbolinks/TurbolinksServiceProvider.php#L28) to automagically load turbolinks assets with the Larasset package.

If you agree, I could send you a pull request by the end of the week. With an additional `README_LARASSET.md` file.

Merci d'avance,
Tortue Torche

**Comment by MathieuDoyon** [comment]
Yes absolutely.  Send me your problem,  I will merge it to support L5

**Comment by MathieuDoyon** [comment]
Your PR -  * auto-correct

**Comment by tortuetorche** [comment]
There is some drawbacks, my Laravel 5 support isn't backwards compatible with Laravel 4.
IMO, the best solution is to create two git branches. I already to this in my tubolink fork: 
  * The [`0.9` branch](https://github.com/efficiently/turbolinks/tree/0.9) is for Laravel 4.1+
 *  The [`1.0` branch](https://github.com/efficiently/turbolinks/tree/1.0) is for Laravel 5.0+

Are you OK with this?

**Comment by tortuetorche** [comment]
Hi @MathieuDoyon,

Can you create a new branch, please?
Then I'll send a pull request to it.

A+,
Tortue Torche

**Comment by MathieuDoyon** [comment]
https://github.com/frenzyapp/turbolinks/tree/L5

**Comment by tortuetorche** [comment]
:+1:

**Comment by tortuetorche** [comment]
See #7
