### ISSUE TITLE
Update to turbolinks 3?

### ISSUE THREAD

**Issue by jeepey** [frenzyapp/turbolinks#9]
Hi,

Turbolinks 3 provides support for partial updates, which I think is a great feature.

Are there any plans to update this repo to support turbolinks 3?

Thanks!

**Comment by tortuetorche** [comment]
Hi @jeepey, you can see https://github.com/efficiently/turbolinks/tree/turbo3 and https://github.com/tortuetorche/Turbolinks/tree/turbo3 
Still WIP but you can test it with this demo:https://github.com/efficiently/laravel_larasset_app/tree/turbo3-l5.1

**Comment by jeepey** [comment]
Thanks @tortuetorche ! I'll have a look

**Comment by tortuetorche** [comment]
@jeepey You're welcome, my goal is to merge these changes in this repository and in the [helthe](https://github.com/helthe/Turbolinks/pull/6)'s repository.

**Comment by tortuetorche** [comment]
Good news, this package supports Turbolinks 5 since commit https://github.com/frenzyapp/turbolinks/commit/ab5be2189c3d7330eb7430718f06eadfe2e9c487 (#12)

So, I close this issue.
